
const PAYMENT_METHOD = {
  CREDIT_CARD:'card',
  KAKAO_PAY:'kakaopay',
  NAVER_PAY:'naverpay',
} as const;

const PG_CHANNEL_KEY = {
  GENERAL:{
    CREDIT_CARD: process.env.NEXT_PUBLIC_IAMPORT_GENERAL_KCP_CHANNEL_KEY ?? "",
    KAKAO_PAY: process.env.NEXT_PUBLIC_IAMPORT_GENERAL_KAKAOPAY_CHANNEL_KEY ?? "",
    NAVER_PAY: process.env.NEXT_PUBLIC_IAMPORT_GENERAL_NAVERPAY_CHANNEL_KEY ?? "",
  },
  SUBSCRIPTION:{
    CREDIT_CARD: process.env.NEXT_PUBLIC_IAMPORT_SUBSCRIPTION_KCP_CHANNEL_KEY ?? "",
    KAKAO_PAY: process.env.NEXT_PUBLIC_IAMPORT_SUBSCRIPTION_KAKAOPAY_CHANNEL_KEY ?? "",
    NAVER_PAY: process.env.NEXT_PUBLIC_IAMPORT_SUBSCRIPTION_NAVERPAY_CHANNEL_KEY ?? "",
  }
} as const;


const IAMPORT_MIN_PAYMENT_PRICE = 100;

export { PAYMENT_METHOD, PG_CHANNEL_KEY, IAMPORT_MIN_PAYMENT_PRICE };