
const PET_GENDER = {
	MALE: '수컷',
	FEMALE: '암컷',
} as const;

const PET_TYPE = [
	{ label: "품종 모름", value: "품종 모름" },
	{ label: "믹스", value: "믹스" },
	{ label: "골든 리트리버", value: "골든 리트리버" },
	{ label: "골든두들", value: "골든두들" },
	{ label: "그레이 하운드", value: "그레이 하운드" },
	{ label: "그레이트 데인", value: "그레이트 데인" },
	{ label: "그레이트 피레니즈", value: "그레이트 피레니즈" },
	{ label: "그린란드견", value: "그린란드견" },
	{ label: "기슈견", value: "기슈견" },
	{ label: "꼬똥 드 툴레아", value: "꼬똥 드 툴레아" },
	{ label: "나폴리탄 마스티프", value: "나폴리탄 마스티프" },
	{ label: "뉴기니고산개", value: "뉴기니고산개" },
	{ label: "뉴펀들랜드", value: "뉴펀들랜드" },
	{ label: "닥스훈트", value: "닥스훈트" },
	{ label: "도고 아르헨티노", value: "도고 아르헨티노" },
	{ label: "도베르만 핀셔", value: "도베르만 핀셔" },
	{ label: "라사압소", value: "라사압소" },
	{ label: "라페이로 도 알렌테조", value: "라페이로 도 알렌테조" },
	{ label: "래브라도 리트리버", value: "래브라도 리트리버" },
	{ label: "레온베르거", value: "레온베르거" },
	{ label: "로트와일러", value: "로트와일러" },
	{ label: "마스티프", value: "마스티프" },
	{ label: "말티즈", value: "말티즈" },
	{ label: "미니어처 슈나우저", value: "미니어처 슈나우저" },
	{ label: "미니어처 핀셔", value: "미니어처 핀셔" },
	{ label: "바셋 하운드", value: "바셋 하운드" },
	{ label: "베들링턴 테리어", value: "베들링턴 테리어" },
	{ label: "벨지언 쉽독", value: "벨지언 쉽독" },
	{ label: "보더 콜리", value: "보더 콜리" },
	{ label: "보르도 마스티프", value: "보르도 마스티프" },
	{ label: "보르조이", value: "보르조이" },
	{ label: "보비에 드 플랜더스", value: "보비에 드 플랜더스" },
	{ label: "보스턴 테리어", value: "보스턴 테리어" },
	{ label: "복서", value: "복서" },
	{ label: "불도그", value: "불도그" },
	{ label: "불리 쿠타", value: "불리 쿠타" },
	{ label: "브리어드", value: "브리어드" },
	{ label: "블러드 하운드", value: "블러드 하운드" },
	{ label: "비글", value: "비글" },
	{ label: "비숑 프리제", value: "비숑 프리제" },
	{ label: "빠삐용", value: "빠삐용" },
	{ label: "사모예드", value: "사모예드" },
	{ label: "사플라니낙", value: "사플라니낙" },
	{ label: "삽살개", value: "삽살개" },
	{ label: "샤페이", value: "샤페이" },
	{ label: "세인트 버나드", value: "세인트 버나드" },
	{ label: "솔로이츠 쿠인틀레", value: "솔로이츠 쿠인틀레" },
	{ label: "스코티쉬 테리어", value: "스코티쉬 테리어" },
	{ label: "스키퍼키", value: "스키퍼키" },
	{ label: "스피츠", value: "스피츠" },
	{ label: "시코쿠견", value: "시코쿠견" },
	{ label: "실키 테리어", value: "실키 테리어" },
	{ label: "아메리칸 불리", value: "아메리칸 불리" },
	{
		label: "아메리칸 스태퍼드셔 테리어",
		value: "아메리칸 스태퍼드셔 테리어",
	},
	{ label: "아이디", value: "아이디" },
	{ label: "아키타견", value: "아키타견" },
	{ label: "아펜핀셔", value: "아펜핀셔" },
	{ label: "아프간 하운드", value: "아프간 하운드" },
	{ label: "알래스칸 클리카이", value: "알래스칸 클리카이" },
	{ label: "에스트렐라 마운틴 독", value: "에스트렐라 마운틴 독" },
	{ label: "오브차카", value: "오브차카" },
	{ label: "요크셔 테리어", value: "요크셔 테리어" },
	{
		label: "웨스트 하이랜드 화이트테리어",
		value: "웨스트 하이랜드 화이트테리어",
	},
	{ label: "재패니즈 스피츠", value: "재패니즈 스피츠" },
	{ label: "재패니즈 친", value: "재패니즈 친" },
	{ label: "잭 러셀 테리어", value: "잭 러셀 테리어" },
	{ label: "저먼 셰퍼드", value: "저먼 셰퍼드" },
	{ label: "제주개", value: "제주개" },
	{ label: "진돗개", value: "진돗개" },
	{ label: "차우차우", value: "차우차우" },
	{ label: "치와와", value: "치와와" },
	{ label: "카네 코르소", value: "카네 코르소" },
	{
		label: "카발리에 킹 찰스 스파니엘",
		value: "카발리에 킹 찰스 스파니엘",
	},
	{ label: "코리안 마스티프", value: "코리안 마스티프" },
	{ label: "코몬도르", value: "코몬도르" },
	{ label: "코커 스파니엘", value: "코커 스파니엘" },
	{ label: "콜리", value: "콜리" },
	{ label: "고든 세터", value: "고든 세터" },
	{
		label: "그레이트 스위스 마운틴 도그",
		value: "그레이트 스위스 마운틴 도그",
	},
	{ label: "글렌 오브 이말 테리어", value: "글렌 오브 이말 테리어" },
	{ label: "노르웨지안 부훈트", value: "노르웨지안 부훈트" },
	{ label: "노르웨이 엘크 하운드", value: "노르웨이 엘크 하운드" },
	{ label: "노리치 테리어", value: "노리치 테리어" },
	{
		label: "노바 스코셔 덕 톨링 레트리버",
		value: "노바 스코셔 덕 톨링 레트리버",
	},
	{ label: "노퍽 테리어", value: "노퍽 테리어" },
	{ label: "댄디 딘몬트 테리어", value: "댄디 딘몬트 테리어" },
	{ label: "도고 까나리오", value: "도고 까나리오" },
	{ label: "도그 드 보르도", value: "도그 드 보르도" },
	{ label: "도사견", value: "도사견" },
	{ label: "동경이", value: "동경이" },
	{ label: "라포니안 허더", value: "라포니안 허더" },
	{ label: "레이크랜드 테리어", value: "레이크랜드 테리어" },
	{ label: "로디지아 리지백", value: "로디지아 리지백" },
	{ label: "로첸", value: "로첸" },
	{ label: "미니어처 불 테리어", value: "미니어처 불 테리어" },
	{ label: "바센지", value: "바센지" },
	{ label: "버니즈 마운틴 도그", value: "버니즈 마운틴 도그" },
	{ label: "벨기에 말리노이즈", value: "벨기에 말리노이즈" },
	{ label: "벨기에 테뷰런", value: "벨기에 테뷰런" },
	{ label: "벨지안 그리펀", value: "벨지안 그리펀" },
	{ label: "보더 테리어", value: "보더 테리어" },
	{ label: "보스롱", value: "보스롱" },
	{ label: "볼로네즈", value: "볼로네즈" },
	{ label: "불 마스티프", value: "불 마스티프" },
	{ label: "불 테리어", value: "불 테리어" },
	{ label: "브뤼셀 그리펀", value: "브뤼셀 그리펀" },
	{ label: "브리타니", value: "브리타니" },
	{ label: "블랙 러시안 테리어", value: "블랙 러시안 테리어" },
	{ label: "블랙 앤드 탄 쿤하운드", value: "블랙 앤드 탄 쿤하운드" },
	{ label: "비어디드 콜리", value: "비어디드 콜리" },
	{ label: "비즐라", value: "비즐라" },
	{ label: "살루키", value: "살루키" },
	{ label: "서식스 스패니얼", value: "서식스 스패니얼" },
	{ label: "셔틀랜드 쉽독", value: "셔틀랜드 쉽독" },
	{
		label: "소프트 코티드 휘튼 테리어",
		value: "소프트 코티드 휘튼 테리어",
	},
	{ label: "스무스 폭스 테리어", value: "스무스 폭스 테리어" },
	{ label: "스웨디쉬 발훈트", value: "스웨디쉬 발훈트" },
	{ label: "스카이 테리어", value: "스카이 테리어" },
	{ label: "스코티시 디어하운드", value: "스코티시 디어하운드" },
	{ label: "스태퍼드셔 불 테리어", value: "스태퍼드셔 불 테리어" },
	{ label: "스탠더드 슈나우저", value: "스탠더드 슈나우저" },
	{ label: "스패니쉬 그레이 하운드", value: "스패니쉬 그레이 하운드" },
	{ label: "스패니쉬 마스티프", value: "스패니쉬 마스티프" },
	{ label: "스피노네 이탈리아노", value: "스피노네 이탈리아노" },
	{ label: "시바 이누", value: "시바 이누" },
	{ label: "실리엄 테리어", value: "실리엄 테리어" },
	{ label: "아메리칸 불도그", value: "아메리칸 불도그" },
	{ label: "아메리칸 아키다", value: "아메리칸 아키다" },
	{ label: "아메리칸 에스키모 도그", value: "아메리칸 에스키모 도그" },
	{ label: "아메리칸 워터 스패니얼", value: "아메리칸 워터 스패니얼" },
	{ label: "아메리칸 코커 스패니얼", value: "아메리칸 코커 스패니얼" },
	{ label: "아메리칸 폭스하운드", value: "아메리칸 폭스하운드" },
	{
		label: "아이리시 소프트코티드 휘튼 테리어",
		value: "아이리시 소프트코티드 휘튼 테리어",
	},
	{
		label: "아이리시 레드 앤드 화이트 세터",
		value: "아이리시 레드 앤드 화이트 세터",
	},
	{ label: "아이리시 세터", value: "아이리시 세터" },
	{ label: "아이리시 울프 하운드", value: "아이리시 울프 하운드" },
	{ label: "아이리시 워터 스패니얼", value: "아이리시 워터 스패니얼" },
	{ label: "아이리시 테리어", value: "아이리시 테리어" },
	{ label: "알래스칸 맬러뮤트", value: "알래스칸 맬러뮤트" },
	{ label: "에어데일 테리어", value: "에어데일 테리어" },
	{
		label: "오스트레일리안 실키 테리어",
		value: "오스트레일리안 실키 테리어",
	},
	{ label: "오스트레일리안 켈피", value: "오스트레일리안 켈피" },
	{ label: "오스트레일리안 셰퍼드", value: "오스트레일리안 셰퍼드" },
	{
		label: "오스트레일리안 캐틀 도그",
		value: "오스트레일리안 캐틀 도그",
	},
	{ label: "오스트레일리안 테리어", value: "오스트레일리안 테리어" },
	{ label: "오터 하운드", value: "오터 하운드" },
	{ label: "올드 잉글리시 쉽독", value: "올드 잉글리시 쉽독" },
	{ label: "와이머라너", value: "와이머라너" },
	{ label: "와이어 폭스 테리어", value: "와이어 폭스 테리어" },
	{
		label: "와이어헤어드 포인팅 그리펀",
		value: "와이어헤어드 포인팅 그리펀",
	},
	{ label: "웰시 스프링어 스패니얼", value: "웰시 스프링어 스패니얼" },
	{ label: "웰시 테리어", value: "웰시 테리어" },
	{ label: "이비전 하운드", value: "이비전 하운드" },
	{ label: "이탤리언 그레이하운드", value: "이탤리언 그레이하운드" },
	{ label: "잉글리시 세터", value: "잉글리시 세터" },
	{
		label: "잉글리시 스프링어 스패니얼",
		value: "잉글리시 스프링어 스패니얼",
	},
	{ label: "잉글리시 코커 스패니얼", value: "잉글리시 코커 스패니얼" },
	{ label: "잉글리시 토이 스패니얼", value: "잉글리시 토이 스패니얼" },
	{ label: "잉글리시 폭스하운드", value: "잉글리시 폭스하운드" },
	{ label: "자이언트 슈나우저", value: "자이언트 슈나우저" },
	{ label: "저먼 쇼트헤어드 포인터", value: "저먼 쇼트헤어드 포인터" },
	{
		label: "저먼 와이어헤어드 포인터",
		value: "저먼 와이어헤어드 포인터",
	},
	{ label: "저먼 핀셔", value: "저먼 핀셔" },
	{ label: "저먼 헌팅 테리어", value: "저먼 헌팅 테리어" },
	{ label: "차이니즈 샤페이", value: "차이니즈 샤페이" },
	{ label: "차이니즈 크레스티드", value: "차이니즈 크레스티드" },
	{ label: "체서피크 베이 레트리버", value: "체서피크 베이 레트리버" },
	{ label: "카디건 웰시 코기", value: "카디건 웰시 코기" },
	{ label: "컬리코티드 레트리버", value: "컬리코티드 레트리버" },
	{ label: "케리 블루 테리어", value: "케리 블루 테리어" },
	{ label: "케언 테리어", value: "케언 테리어" },
	{ label: "케이넌 도그", value: "케이넌 도그" },
	{ label: "케이스혼트", value: "케이스혼트" },
	{ label: "쿠바스", value: "쿠바스" },
	{ label: "쿠이커혼제", value: "쿠이커혼제" },
	{ label: "클럼버 스패니얼", value: "클럼버 스패니얼" },
	{ label: "토이 폭스 테리어", value: "토이 폭스 테리어" },
	{ label: "티베탄 마스티프", value: "티베탄 마스티프" },
	{ label: "티베탄 스패니얼", value: "티베탄 스패니얼" },
	{ label: "티베탄 테리어", value: "티베탄 테리어" },
	{ label: "파라오 하운드", value: "파라오 하운드" },
	{ label: "파슨 러셀 테리어", value: "파슨 러셀 테리어" },
	{ label: "패터데일 테리어", value: "패터데일 테리어" },
	{ label: "퍼그", value: "퍼그" },
	{ label: "페키니즈", value: "페키니즈" },
	{ label: "펨브록 웰시 코기", value: "펨브록 웰시 코기" },
	{ label: "포르투기즈 워터 도그", value: "포르투기즈 워터 도그" },
	{ label: "포메라니안", value: "포메라니안" },
	{ label: "포인터", value: "포인터" },
	{ label: "폭스 테리어", value: "폭스 테리어" },
	{ label: "폴리시 롤런드 시프도그", value: "폴리시 롤런드 시프도그" },
	{ label: "폼피츠", value: "폼피츠" },
	{ label: "푸미", value: "푸미" },
	{ label: "풀리", value: "풀리" },
	{ label: "풍산개", value: "풍산개" },
	{ label: "프렌치 불도그", value: "프렌치 불도그" },
	{ label: "프티 바세 그리퐁 방댕", value: "프티 바세 그리퐁 방댕" },
	{ label: "플랫코티드 레트리버", value: "플랫코티드 레트리버" },
	{ label: "플롯 하운드", value: "플롯 하운드" },
	{ label: "피니시 스피츠", value: "피니시 스피츠" },
	{ label: "피레니안 마스티프", value: "피레니안 마스티프" },
	{ label: "피레니안 쉽독", value: "피레니안 쉽독" },
	{ label: "피레니안 셰퍼드", value: "피레니안 셰퍼드" },
	{ label: "필드 스패니얼", value: "필드 스패니얼" },
	{ label: "필라 브라질레이로", value: "필라 브라질레이로" },
	{ label: "핏 불 테리어", value: "핏 불 테리어" },
	{ label: "해리어", value: "해리어" },
	{ label: "하바니즈", value: "하바니즈" },
	{ label: "홋카이도 이누", value: "홋카이도 이누" },
	{ label: "휘핏", value: "휘핏" },
	{ label: "달마시안", value: "달마시안" },
	{ label: "시베리안 허스키", value: "시베리안 허스키" },
	{ label: "시추", value: "시추" },
	{ label: "말티푸", value: "말티푸" },
	{
		label: "맨체스터 테리어(스탠다드)",
		value: "맨체스터 테리어(스탠다드)",
	},
	{ label: "맨체스터 테리어(토이)", value: "맨체스터 테리어(토이)" },
	{ label: "푸들(미니어처)", value: "푸들(미니어처)" },
	{ label: "푸들(스탠다드)", value: "푸들(스탠다드)" },
	{ label: "푸들(토이)", value: "푸들(토이)" },
	{ label: "아나톨리아 셰퍼드(캉갈)", value: "아나톨리아 셰퍼드(캉갈)" },
]

export { 
	PET_GENDER, 
	PET_TYPE, 
};