export {queryKeys}

const queryKeys = {
  SURVEY: 'survey',
  GET_SURVEY_RECIPE: 'getSurveyRecipe',
  GET_SURVEY_RESULT: 'getSurveyResult',
  COUPON: 'coupon',
  GET_COUPON_LIST: 'getCouponList',
  MYPAGE: 'mypage',
  GET_MYPAGE_INFO: 'getMypageInfo',
  GET_DOGS: 'getDogs',
  REWARDS: 'rewards',
  GET_REWARDS_LIST: 'getRewards',
  SUBSCRIBE: 'subscribe',
  GET_SUBSCRIPTION_BY_ID: 'getSubscriptionById',
  SUBSCRIPTION: 'subscription',
  GET_PLAN_DISCOUNT: 'getPlanDiscount',
  GET_ORDER_SHEET: 'getOrderSheet',
  SKIP_SUBSCRIPTION: 'skipSubscription',
  ORDER: 'order',
  ORDER_DETAIL: 'orderDetail',
  GET_SUBSCRIBE_ORDER_LIST: 'getSubscribeOrderList',
  GET_GENERAL_ORDER_LIST: 'getGeneralOrderList',
  GET_SUBSCRIBE_LIST: 'getSubscribeList',
  GET_PACKAGE_BENEFITS: 'getPackageBenefits',
  GET_DELIVERY_ADDRESS: 'getDeliveryAddress',
} as const