import { SurveyStepKeys } from "@/utils/validation/surveyValidation";

export {
  SURVEY_FORM_INFO,
  RECIPE_TEMP_DATA,
  SURVEY_NO_AUTO_NEXT_STEP,
  SURVEY_OPTIONAL_FIELDS,
  NONE_VALUE,
  SURVEY_SECTIONS,
  SURVEY_TITLES,
};

const SURVEY_SECTIONS = [
  { key: "dogBasicInfo", label: "기본 정보", steps: 6 },
  { key: "dogLifestyle", label: "생활 정보", steps: 5 },
  { key: "dogDietHealth", label: "식단/건강", steps: 3 },
];

export type SurveyTitleTemplates = {
  [stepKey in SurveyStepKeys]: string[];
};

const SURVEY_TITLES: SurveyTitleTemplates = {
  step1: ["반려견에 대해 알려주세요"],
  step2: ["{petName}의", "생년월일은 언제인가요?"],
  step3: ["{petName}의", "몸무게는 얼마인가요?"],
  step4: ["{petName}의", "견종은 무엇인가요?"],
  step5: ["현재", "임신 중인가요?"],
  step6: ["현재", "수유 중인가요?"],
  step7: ["{petName}의", "체형은 어느 쪽에 가까운가요?"],
  step8: ["{petName}의", "활동량은 어떤가요?"],
  step9: ["{petName}의", "간식량은 어떤가요?"],
  step10: ["못 먹는 재료는", "무엇인가요?"],
  step11: ["{petName}의", "건강고민은 무엇인가요?"],
  step12: ["현재 먹고 있는", "사료는 무엇인가요?"],
  step13: ["현재 먹고 있는", "영양제가 있나요?"],
  step14: ["아래의 질병 중", "앓고 있는 질병이 있나요?"],
};

const SURVEY_FORM_INFO = {
  dogBasicInfo: {
    gender: {
      id: "gender",
      title: "성별",
      inputType: "radio",
      options: [
        {
          id: "gender-female",
          value: "female",
          label: "암컷",
          imageUrl: "/images/survey/female.png",
        },
        {
          id: "gender-male",
          value: "male",
          label: "수컷",
          imageUrl: "/images/survey/male.png",
        },
      ],
    },
    name: {
      id: "name",
      title: "이름",
      inputType: "textField",
      placeholder: "이름을 입력해주세요",
    },
    isNeutered: {
      id: "isNeutered",
      title: "중성화 여부",
      inputType: "radio",
      options: [
        { id: "isNeutered-true", value: true, label: "중성화 했어요" },
        { id: "isNeutered-false", value: false, label: "중성화 안했어요" },
      ],
    },
    birthDate: {
      id: "birthDate",
      inputType: "textField",
      placeholder: "생년월 (YYYY-MM) 입력",
    },
    isSenior: {
      id: "isSenior",
      title: "노령견",
      inputType: "radio",
      options: [
        { id: "isSenior-true", value: true, label: "노령견이에요" },
        { id: "isSenior-false", value: false, label: "노령견이 아니에요" },
      ],
    },
    dogSize: {
      id: "dogSize",
      title: "견사이즈",
      inputType: "radio",
      options: [
        {
          id: "dogSize-small",
          value: "small",
          label: "소형",
          imageUrl: "/images/survey/small-dog.png",
        },
        {
          id: "dogSize-medium",
          value: "medium",
          label: "중형",
          imageUrl: "/images/survey/medium-dog.png",
        },
        {
          id: "dogSize-large",
          value: "large",
          label: "대형",
          imageUrl: "/images/survey/large-dog.png",
        },
      ],
    },
    weight: {
      id: "weight",
      title: "몸무게",
      inputType: "textField",
      placeholder: "몸무게 입력",
      unit: "kg",
    },
    dogType: {
      id: "dogType",
      inputType: "radio",
      placeholder: "견종을 검색해 보세요",
      options: [
        { label: "품종 모름", value: "품종 모름" },
        { label: "믹스", value: "믹스" },
        { label: "골든 리트리버", value: "골든 리트리버" },
        { label: "골든두들", value: "골든두들" },
        { label: "그레이 하운드", value: "그레이 하운드" },
        { label: "그레이트 데인", value: "그레이트 데인" },
        { label: "그레이트 피레니즈", value: "그레이트 피레니즈" },
        { label: "그린란드견", value: "그린란드견" },
        { label: "기슈견", value: "기슈견" },
        { label: "꼬똥 드 툴레아", value: "꼬똥 드 툴레아" },
        { label: "나폴리탄 마스티프", value: "나폴리탄 마스티프" },
        { label: "뉴기니고산개", value: "뉴기니고산개" },
        { label: "뉴펀들랜드", value: "뉴펀들랜드" },
        { label: "닥스훈트", value: "닥스훈트" },
        { label: "도고 아르헨티노", value: "도고 아르헨티노" },
        { label: "도베르만 핀셔", value: "도베르만 핀셔" },
        { label: "라사압소", value: "라사압소" },
        { label: "라페이로 도 알렌테조", value: "라페이로 도 알렌테조" },
        { label: "래브라도 리트리버", value: "래브라도 리트리버" },
        { label: "레온베르거", value: "레온베르거" },
        { label: "로트와일러", value: "로트와일러" },
        { label: "마스티프", value: "마스티프" },
        { label: "말티즈", value: "말티즈" },
        { label: "미니어처 슈나우저", value: "미니어처 슈나우저" },
        { label: "미니어처 핀셔", value: "미니어처 핀셔" },
        { label: "바셋 하운드", value: "바셋 하운드" },
        { label: "베들링턴 테리어", value: "베들링턴 테리어" },
        { label: "벨지언 쉽독", value: "벨지언 쉽독" },
        { label: "보더 콜리", value: "보더 콜리" },
        { label: "보르도 마스티프", value: "보르도 마스티프" },
        { label: "보르조이", value: "보르조이" },
        { label: "보비에 드 플랜더스", value: "보비에 드 플랜더스" },
        { label: "보스턴 테리어", value: "보스턴 테리어" },
        { label: "복서", value: "복서" },
        { label: "불도그", value: "불도그" },
        { label: "불리 쿠타", value: "불리 쿠타" },
        { label: "브리어드", value: "브리어드" },
        { label: "블러드 하운드", value: "블러드 하운드" },
        { label: "비글", value: "비글" },
        { label: "비숑 프리제", value: "비숑 프리제" },
        { label: "빠삐용", value: "빠삐용" },
        { label: "사모예드", value: "사모예드" },
        { label: "사플라니낙", value: "사플라니낙" },
        { label: "삽살개", value: "삽살개" },
        { label: "샤페이", value: "샤페이" },
        { label: "세인트 버나드", value: "세인트 버나드" },
        { label: "솔로이츠 쿠인틀레", value: "솔로이츠 쿠인틀레" },
        { label: "스코티쉬 테리어", value: "스코티쉬 테리어" },
        { label: "스키퍼키", value: "스키퍼키" },
        { label: "스피츠", value: "스피츠" },
        { label: "시코쿠견", value: "시코쿠견" },
        { label: "실키 테리어", value: "실키 테리어" },
        { label: "아메리칸 불리", value: "아메리칸 불리" },
        {
          label: "아메리칸 스태퍼드셔 테리어",
          value: "아메리칸 스태퍼드셔 테리어",
        },
        { label: "아이디", value: "아이디" },
        { label: "아키타견", value: "아키타견" },
        { label: "아펜핀셔", value: "아펜핀셔" },
        { label: "아프간 하운드", value: "아프간 하운드" },
        { label: "알래스칸 클리카이", value: "알래스칸 클리카이" },
        { label: "에스트렐라 마운틴 독", value: "에스트렐라 마운틴 독" },
        { label: "오브차카", value: "오브차카" },
        { label: "요크셔 테리어", value: "요크셔 테리어" },
        {
          label: "웨스트 하이랜드 화이트테리어",
          value: "웨스트 하이랜드 화이트테리어",
        },
        { label: "재패니즈 스피츠", value: "재패니즈 스피츠" },
        { label: "재패니즈 친", value: "재패니즈 친" },
        { label: "잭 러셀 테리어", value: "잭 러셀 테리어" },
        { label: "저먼 셰퍼드", value: "저먼 셰퍼드" },
        { label: "제주개", value: "제주개" },
        { label: "진돗개", value: "진돗개" },
        { label: "차우차우", value: "차우차우" },
        { label: "치와와", value: "치와와" },
        { label: "카네 코르소", value: "카네 코르소" },
        {
          label: "카발리에 킹 찰스 스파니엘",
          value: "카발리에 킹 찰스 스파니엘",
        },
        { label: "코리안 마스티프", value: "코리안 마스티프" },
        { label: "코몬도르", value: "코몬도르" },
        { label: "코커 스파니엘", value: "코커 스파니엘" },
        { label: "콜리", value: "콜리" },
        { label: "고든 세터", value: "고든 세터" },
        {
          label: "그레이트 스위스 마운틴 도그",
          value: "그레이트 스위스 마운틴 도그",
        },
        { label: "글렌 오브 이말 테리어", value: "글렌 오브 이말 테리어" },
        { label: "노르웨지안 부훈트", value: "노르웨지안 부훈트" },
        { label: "노르웨이 엘크 하운드", value: "노르웨이 엘크 하운드" },
        { label: "노리치 테리어", value: "노리치 테리어" },
        {
          label: "노바 스코셔 덕 톨링 레트리버",
          value: "노바 스코셔 덕 톨링 레트리버",
        },
        { label: "노퍽 테리어", value: "노퍽 테리어" },
        { label: "댄디 딘몬트 테리어", value: "댄디 딘몬트 테리어" },
        { label: "도고 까나리오", value: "도고 까나리오" },
        { label: "도그 드 보르도", value: "도그 드 보르도" },
        { label: "도사견", value: "도사견" },
        { label: "동경이", value: "동경이" },
        { label: "라포니안 허더", value: "라포니안 허더" },
        { label: "레이크랜드 테리어", value: "레이크랜드 테리어" },
        { label: "로디지아 리지백", value: "로디지아 리지백" },
        { label: "로첸", value: "로첸" },
        { label: "미니어처 불 테리어", value: "미니어처 불 테리어" },
        { label: "바센지", value: "바센지" },
        { label: "버니즈 마운틴 도그", value: "버니즈 마운틴 도그" },
        { label: "벨기에 말리노이즈", value: "벨기에 말리노이즈" },
        { label: "벨기에 테뷰런", value: "벨기에 테뷰런" },
        { label: "벨지안 그리펀", value: "벨지안 그리펀" },
        { label: "보더 테리어", value: "보더 테리어" },
        { label: "보스롱", value: "보스롱" },
        { label: "볼로네즈", value: "볼로네즈" },
        { label: "불 마스티프", value: "불 마스티프" },
        { label: "불 테리어", value: "불 테리어" },
        { label: "브뤼셀 그리펀", value: "브뤼셀 그리펀" },
        { label: "브리타니", value: "브리타니" },
        { label: "블랙 러시안 테리어", value: "블랙 러시안 테리어" },
        { label: "블랙 앤드 탄 쿤하운드", value: "블랙 앤드 탄 쿤하운드" },
        { label: "비어디드 콜리", value: "비어디드 콜리" },
        { label: "비즐라", value: "비즐라" },
        { label: "살루키", value: "살루키" },
        { label: "서식스 스패니얼", value: "서식스 스패니얼" },
        { label: "셔틀랜드 쉽독", value: "셔틀랜드 쉽독" },
        {
          label: "소프트 코티드 휘튼 테리어",
          value: "소프트 코티드 휘튼 테리어",
        },
        { label: "스무스 폭스 테리어", value: "스무스 폭스 테리어" },
        { label: "스웨디쉬 발훈트", value: "스웨디쉬 발훈트" },
        { label: "스카이 테리어", value: "스카이 테리어" },
        { label: "스코티시 디어하운드", value: "스코티시 디어하운드" },
        { label: "스태퍼드셔 불 테리어", value: "스태퍼드셔 불 테리어" },
        { label: "스탠더드 슈나우저", value: "스탠더드 슈나우저" },
        { label: "스패니쉬 그레이 하운드", value: "스패니쉬 그레이 하운드" },
        { label: "스패니쉬 마스티프", value: "스패니쉬 마스티프" },
        { label: "스피노네 이탈리아노", value: "스피노네 이탈리아노" },
        { label: "시바 이누", value: "시바 이누" },
        { label: "실리엄 테리어", value: "실리엄 테리어" },
        { label: "아메리칸 불도그", value: "아메리칸 불도그" },
        { label: "아메리칸 아키다", value: "아메리칸 아키다" },
        { label: "아메리칸 에스키모 도그", value: "아메리칸 에스키모 도그" },
        { label: "아메리칸 워터 스패니얼", value: "아메리칸 워터 스패니얼" },
        { label: "아메리칸 코커 스패니얼", value: "아메리칸 코커 스패니얼" },
        { label: "아메리칸 폭스하운드", value: "아메리칸 폭스하운드" },
        {
          label: "아이리시 소프트코티드 휘튼 테리어",
          value: "아이리시 소프트코티드 휘튼 테리어",
        },
        {
          label: "아이리시 레드 앤드 화이트 세터",
          value: "아이리시 레드 앤드 화이트 세터",
        },
        { label: "아이리시 세터", value: "아이리시 세터" },
        { label: "아이리시 울프 하운드", value: "아이리시 울프 하운드" },
        { label: "아이리시 워터 스패니얼", value: "아이리시 워터 스패니얼" },
        { label: "아이리시 테리어", value: "아이리시 테리어" },
        { label: "알래스칸 맬러뮤트", value: "알래스칸 맬러뮤트" },
        { label: "에어데일 테리어", value: "에어데일 테리어" },
        {
          label: "오스트레일리안 실키 테리어",
          value: "오스트레일리안 실키 테리어",
        },
        { label: "오스트레일리안 켈피", value: "오스트레일리안 켈피" },
        { label: "오스트레일리안 셰퍼드", value: "오스트레일리안 셰퍼드" },
        {
          label: "오스트레일리안 캐틀 도그",
          value: "오스트레일리안 캐틀 도그",
        },
        { label: "오스트레일리안 테리어", value: "오스트레일리안 테리어" },
        { label: "오터 하운드", value: "오터 하운드" },
        { label: "올드 잉글리시 쉽독", value: "올드 잉글리시 쉽독" },
        { label: "와이머라너", value: "와이머라너" },
        { label: "와이어 폭스 테리어", value: "와이어 폭스 테리어" },
        {
          label: "와이어헤어드 포인팅 그리펀",
          value: "와이어헤어드 포인팅 그리펀",
        },
        { label: "웰시 스프링어 스패니얼", value: "웰시 스프링어 스패니얼" },
        { label: "웰시 테리어", value: "웰시 테리어" },
        { label: "이비전 하운드", value: "이비전 하운드" },
        { label: "이탤리언 그레이하운드", value: "이탤리언 그레이하운드" },
        { label: "잉글리시 세터", value: "잉글리시 세터" },
        {
          label: "잉글리시 스프링어 스패니얼",
          value: "잉글리시 스프링어 스패니얼",
        },
        { label: "잉글리시 코커 스패니얼", value: "잉글리시 코커 스패니얼" },
        { label: "잉글리시 토이 스패니얼", value: "잉글리시 토이 스패니얼" },
        { label: "잉글리시 폭스하운드", value: "잉글리시 폭스하운드" },
        { label: "자이언트 슈나우저", value: "자이언트 슈나우저" },
        { label: "저먼 쇼트헤어드 포인터", value: "저먼 쇼트헤어드 포인터" },
        {
          label: "저먼 와이어헤어드 포인터",
          value: "저먼 와이어헤어드 포인터",
        },
        { label: "저먼 핀셔", value: "저먼 핀셔" },
        { label: "저먼 헌팅 테리어", value: "저먼 헌팅 테리어" },
        { label: "차이니즈 샤페이", value: "차이니즈 샤페이" },
        { label: "차이니즈 크레스티드", value: "차이니즈 크레스티드" },
        { label: "체서피크 베이 레트리버", value: "체서피크 베이 레트리버" },
        { label: "카디건 웰시 코기", value: "카디건 웰시 코기" },
        { label: "컬리코티드 레트리버", value: "컬리코티드 레트리버" },
        { label: "케리 블루 테리어", value: "케리 블루 테리어" },
        { label: "케언 테리어", value: "케언 테리어" },
        { label: "케이넌 도그", value: "케이넌 도그" },
        { label: "케이스혼트", value: "케이스혼트" },
        { label: "쿠바스", value: "쿠바스" },
        { label: "쿠이커혼제", value: "쿠이커혼제" },
        { label: "클럼버 스패니얼", value: "클럼버 스패니얼" },
        { label: "토이 폭스 테리어", value: "토이 폭스 테리어" },
        { label: "티베탄 마스티프", value: "티베탄 마스티프" },
        { label: "티베탄 스패니얼", value: "티베탄 스패니얼" },
        { label: "티베탄 테리어", value: "티베탄 테리어" },
        { label: "파라오 하운드", value: "파라오 하운드" },
        { label: "파슨 러셀 테리어", value: "파슨 러셀 테리어" },
        { label: "패터데일 테리어", value: "패터데일 테리어" },
        { label: "퍼그", value: "퍼그" },
        { label: "페키니즈", value: "페키니즈" },
        { label: "펨브록 웰시 코기", value: "펨브록 웰시 코기" },
        { label: "포르투기즈 워터 도그", value: "포르투기즈 워터 도그" },
        { label: "포메라니안", value: "포메라니안" },
        { label: "포인터", value: "포인터" },
        { label: "폭스 테리어", value: "폭스 테리어" },
        { label: "폴리시 롤런드 시프도그", value: "폴리시 롤런드 시프도그" },
        { label: "폼피츠", value: "폼피츠" },
        { label: "푸미", value: "푸미" },
        { label: "풀리", value: "풀리" },
        { label: "풍산개", value: "풍산개" },
        { label: "프렌치 불도그", value: "프렌치 불도그" },
        { label: "프티 바세 그리퐁 방댕", value: "프티 바세 그리퐁 방댕" },
        { label: "플랫코티드 레트리버", value: "플랫코티드 레트리버" },
        { label: "플롯 하운드", value: "플롯 하운드" },
        { label: "피니시 스피츠", value: "피니시 스피츠" },
        { label: "피레니안 마스티프", value: "피레니안 마스티프" },
        { label: "피레니안 쉽독", value: "피레니안 쉽독" },
        { label: "피레니안 셰퍼드", value: "피레니안 셰퍼드" },
        { label: "필드 스패니얼", value: "필드 스패니얼" },
        { label: "필라 브라질레이로", value: "필라 브라질레이로" },
        { label: "핏 불 테리어", value: "핏 불 테리어" },
        { label: "해리어", value: "해리어" },
        { label: "하바니즈", value: "하바니즈" },
        { label: "홋카이도 이누", value: "홋카이도 이누" },
        { label: "휘핏", value: "휘핏" },
        { label: "달마시안", value: "달마시안" },
        { label: "시베리안 허스키", value: "시베리안 허스키" },
        { label: "시추", value: "시추" },
        { label: "말티푸", value: "말티푸" },
        {
          label: "맨체스터 테리어(스탠다드)",
          value: "맨체스터 테리어(스탠다드)",
        },
        { label: "맨체스터 테리어(토이)", value: "맨체스터 테리어(토이)" },
        { label: "푸들(미니어처)", value: "푸들(미니어처)" },
        { label: "푸들(스탠다드)", value: "푸들(스탠다드)" },
        { label: "푸들(토이)", value: "푸들(토이)" },
        { label: "아나톨리아 셰퍼드(캉갈)", value: "아나톨리아 셰퍼드(캉갈)" },
      ],
    },
    pregnancy: {
      id: "pregnancy",
      inputType: "radio",
      title: "",
      options: [
        { id: "pregnancy-none", value: "none", label: "아니요" },
        { id: "pregnancy-early", value: "early", label: "임신 초기" },
        { id: "pregnancy-late", value: "late", label: "임신 후기" },
      ],
    },
    lactation: {
      id: "lactation",
      inputType: "radio",
      title: "",
      options: [
        { id: "lactation-none", value: "none", label: "아니요" },
        { id: "lactation-1", value: 1, label: "1~2마리" },
        { id: "lactation-3", value: 3, label: "3~4마리" },
        { id: "lactation-5", value: 5, label: "5~6마리" },
        { id: "lactation-7", value: 7, label: "7마리 이상" },
      ],
    },
  },
  dogLifestyle: {
    bodyCondition: {
      id: "bodyCondition",
      inputType: "radio",
      title: "",
      options: [
        {
          id: "bodyCondition-veryThin",
          value: "very_thin",
          label: "매우 마름",
          subLabel: "근육이 거의 느껴지지 않음",
        },
        {
          id: "bodyCondition-thin",
          value: "thin",
          label: "마름",
          subLabel: "갈비뼈가 쉽게 만져짐",
        },
        {
          id: "bodyCondition-normal",
          value: "normal",
          label: "적정 체중",
          subLabel: "복부가 위로 올라가 있음",
        },
        {
          id: "bodyCondition-overweight",
          value: "overweight",
          label: "과체중",
          subLabel: "복부가 평평",
        },
        {
          id: "bodyCondition-obese",
          value: "obese",
          label: "심각한 비만",
          subLabel: "복부가 심하게 쳐짐",
        },
      ],
    },
    activityLevel: {
      id: "activityLevel",
      inputType: "radio",
      title: "",
      options: [
        {
          id: "activityLevel-veryHigh",
          value: "very_high",
          label: "매우 많아요",
        },
        { id: "activityLevel-high", value: "high", label: "많아요" },
        { id: "activityLevel-normal", value: "normal", label: "보통이에요" },
        { id: "activityLevel-low", value: "low", label: "적어요" },
        {
          id: "activityLevel-veryLow",
          value: "very_low",
          label: "매우 적어요",
        },
      ],
    },
    snackFrequency: {
      id: "snackFrequency",
      inputType: "radio",
      options: [
        {
          id: "snackFrequency-low",
          value: "low",
          label: "적어요",
          subLabel: "식사에 영향을 주지 않는 양",
        },
        {
          id: "snackFrequency-moderate",
          value: "moderate",
          label: "적당해요",
          subLabel: "어느정도 영향을 주는 양",
        },
        {
          id: "snackFrequency-high",
          value: "high",
          label: "많아요",
          subLabel: "식사에 상당한 영향을 주는 양",
        },
      ],
    },
    allergyIngredients: {
      id: "allergyIngredients",
      inputType: "checkbox",
      options: [
        { id: "allergyIngredients-none", value: "none", label: "없어요" },
        { id: "allergyIngredients-chicken", value: "chicken", label: "닭" },
        { id: "allergyIngredients-turkey", value: "turkey", label: "칠면조" },
        { id: "allergyIngredients-duck", value: "duck", label: "오리" },
        { id: "allergyIngredients-lamb", value: "lamb", label: "양" },
      ],
    },
    healthConcerns: {
      id: "healthConcerns",
      inputType: "checkbox",
      options: [
        {
          id: "healthConcerns-vomiting",
          value: "vomiting_diarrhea",
          label: "구토/설사",
        },
        {
          id: "healthConcerns-weight",
          value: "weight_control",
          label: "체중조절",
        },
        {
          id: "healthConcerns-energy",
          value: "energy_boost",
          label: "기력보충",
        },
        { id: "healthConcerns-tears", value: "tears", label: "눈물/눈곱" },
        { id: "healthConcerns-skin", value: "skin_hair", label: "피부/모질" },
      ],
    },
  },
  dogDietHealth: {
    currentFood: {
      id: "currentFood",
      inputType: "checkbox",
      options: [
        { id: "currentFood-dry", value: "dry", label: "건사료" },
        { id: "currentFood-wet", value: "wet", label: "습식사료" },
        { id: "currentFood-homemade", value: "homemade", label: "홈메이드식" },
        {
          id: "currentFood-freezeDried",
          value: "freeze_dried",
          label: "동결건조",
        },
        { id: "currentFood-cooked", value: "cooked", label: "화식" },
        { id: "currentFood-raw", value: "raw", label: "생식" },
      ],
    },
    currentSupplements: {
      id: "currentSupplements",
      inputType: "checkbox",
      options: [
        { id: "currentSupplements-none", value: "none", label: "없어요" },
        {
          id: "currentSupplements-probioticsOmega3",
          value: "probiotics_omega3",
          label: "유산균 오메가3",
        },
        { id: "currentSupplements-joint", value: "joint", label: "관절" },
        { id: "currentSupplements-eye", value: "eye", label: "눈" },
      ],
    },
    healthIssues: {
      id: "healthIssues",
      inputType: "checkbox",
      options: [
        { id: "healthIssues-none", value: "none", label: "없어요" },
        {
          id: "healthIssues-hyperlipidemia",
          value: "hyperlipidemia",
          label: "고지혈증",
        },
        {
          id: "healthIssues-pancreatic",
          value: "pancreatic",
          label: "췌장질환",
        },
        { id: "healthIssues-heart", value: "heart", label: "심장병" },
        { id: "healthIssues-kidney", value: "kidney", label: "신장병" },
        { id: "healthIssues-dermatitis", value: "dermatitis", label: "피부염" },
      ],
    },
  },
};

export interface RecipeTempData {
  id: number;
  name: string;
  imageURL: string;
  ingredients: string[];
  efficacy: string[];
  type: "single" | "double";
}

export interface TempRecipeDto {
  id: number;
  name: string;
  imageURL: string;
}

const RECIPE_TEMP_DATA: Record<number, RecipeTempData> = {
  5: {
    id: 5,
    name: "스타터 프리미엄",
    imageURL: "/images/recipe/starter_premium.png",
    ingredients: ["닭", "칠면조"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "double",
  },
  6: {
    id: 6,
    name: "터키앤비프",
    imageURL: "/images/recipe/turkey_and_beef.png",
    ingredients: ["칠면조", "소"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "double",
  },
  7: {
    id: 7,
    name: "덕앤램",
    imageURL: "/images/recipe/duck_and_lamb.png",
    ingredients: ["오리", "양"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "double",
  },
  8: {
    id: 8,
    name: "램앤비프",
    imageURL: "/images/recipe/lamb_and_beef.png",
    ingredients: ["양", "소"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "double",
  },
  9: {
    id: 9,
    name: "프리미엄 치킨",
    imageURL: "/images/recipe/premium_chicken.png",
    ingredients: ["닭"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "single",
  },
  10: {
    id: 10,
    name: "프리미엄 터키",
    imageURL: "/images/recipe/premium_turkey.png",
    ingredients: ["칠면조"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "single",
  },
  11: {
    id: 11,
    name: "프리미엄 램",
    imageURL: "/images/recipe/premium_lamb.png",
    ingredients: [""],
    efficacy: ["구토•설사", "관절 건강"],
    type: "single",
  },
  12: {
    id: 12,
    name: "프리미엄 비프",
    imageURL: "/images/recipe/premium_beef.png",
    ingredients: ["양"],
    efficacy: ["구토•설사", "관절 건강"],
    type: "single",
  },
};

// 자동 다음 스텝으로 넘어가지 말아야 하는 스텝들을 Set으로 관리.
const SURVEY_NO_AUTO_NEXT_STEP = new Set<SurveyStepKeys>([
  "step3",
  "step10",
  "step11",
  "step12",
  "step13",
  "step14",
]);

// 빈 값이어도 검증 통과 시킬 필드들을 관리합니다.
const SURVEY_OPTIONAL_FIELDS = new Set([
  // step7
  "specificDogStatus",
  "specificDogStatusEtc",
  "expectedPregnancyDay",
  // step12
  "supplementEtc",
  // step13
  "inedibleFoodEtc",
  // step15
  "cautionEtc",
]);

const NONE_VALUE = "none";

// const SURVEY_FORM_INFO_2 = {
//   name: {
//     id: "name",
//     inputType: "textField",
//     title: "반려견 이름이 무엇인가요?",
//     placeholder: "이름을 입력해주세요",
//   },
//   gender: {
//     id: "gender",
//     inputType: "button",
//     title: "의 성별은 무엇인가요?",
//     isMultiSelect: false,
//     options: [
//       { id: "gender-MALE", value: "MALE", label: "수컷" },
//       { id: "gender-FEMALE", value: "FEMALE", label: "암컷" },
//     ],
//   },
//   neutralization: {
//     id: "neutralization",
//     inputType: "button",
//     title: "의 중성화 여부를 알려주세요",
//     isMultiSelect: false,
//     options: [
//       { id: "neutralization했습니다", value: true, label: "했습니다" },
//       { id: "neutralization안했습니다", value: false, label: "안했습니다" },
//     ],
//   },
//   dogSize: {
//     id: "dogSize",
//     inputType: "button",
//     title: "의 견종은 무엇인가요?",
//     isMultiSelect: false,
//     options: [
//       { id: "dogSize-SMALL", value: "SMALL", label: "소형견" },
//       { id: "dogSize-MIDDLE", value: "MIDDLE", label: "중형견" },
//       { id: "dogSize-LARGE", value: "LARGE", label: "대형견" },
//     ],
//   },
//   dogType: {
//     id: "dogType",
//     inputType: "searchableSelectBox",
//     placeholder1: "견종을 선택해주세요.",
//     placeholder2: "견종을 입력해주세요.",
//     options: [
//       "품종 모름",
//       "믹스",
//       "골든 리트리버",
//       "푸들(미니어처)",
//       "푸들(스탠다드)",
//       "푸들(토이)",
//       "아나톨리아 셰퍼드(캉갈)",
//     ],
//   },
//   birth: {
//     id: "birth",
//     inputType: "selectBox",
//     title: "의 출생일은 언제인가요?",
//     years: Array.from({ length: 50 }, (_, i) => {
//       const year = new Date().getFullYear() - i;
//       return {
//         label: `${year}년`,
//         value: year.toString(),
//       };
//     }),
//     months: Array.from({ length: 12 }, (_, i) => {
//       const month = (i + 1).toString().padStart(2, "0");
//       return {
//         label: `${month}월`,
//         value: month,
//       };
//     }),
//   },
//   weight: {
//     id: "weight",
//     inputType: "textField",
//     title: "의 몸무게는 얼마인가요?",
//     placeholder: "몸무게를 입력해주세요",
//     unit: "kg",
//   },
//   dogStatus: {
//     id: "dogStatus",
//     inputType: "button",
//     title: "의 현재 상태는 어떤가요?",
//     isMultiSelect: true,
//     options: [
//       { id: "dogStatus-HEALTHY", value: "HEALTHY", label: "건강해요" },
//       { id: "dogStatus-NEED_DIET", value: "NEED_DIET", label: "다이어트 필요" },
//       { id: "dogStatus-OBESITY", value: "OBESITY", label: "심각한 비만" },
//       { id: "dogStatus-PREGNANT", value: "PREGNANT", label: "임신한 상태" },
//       { id: "dogStatus-LACTATING", value: "LACTATING", label: "수유 중" },
//     ],
//   },
//   activityLevel: {
//     id: "activityLevel",
//     inputType: "button",
//     title: "의 활동량은 어떤가요?",
//     isMultiSelect: false,
//     options: [
//       {
//         id: "activityLevel-VERY_MUCH",
//         value: "VERY_MUCH",
//         label: "매우 많아요",
//       },
//       { id: "activityLevel-MUCH", value: "MUCH", label: "많아요" },
//       { id: "activityLevel-NORMAL", value: "NORMAL", label: "보통" },
//       { id: "activityLevel-LITTLE", value: "LITTLE", label: "적어요" },
//       {
//         id: "activityLevel-VERY_LITTLE",
//         value: "VERY_LITTLE",
//         label: "매우 적어요",
//       },
//     ],
//   },
//   walkingCountPerWeek: {
//     id: "walkingCountPerWeek",
//     inputType: "selectBox",
//     title: "의 산책량은 어떤가요?",
//     frontWord: "주 평균",
//     placeholder: "횟수",
//     options: Array.from({ length: 20 }, (_, i) => {
//       const label = i === 19 ? `${i + 1} 회 이상` : `${i + 1} 회`;
//       return {
//         label,
//         value: (i + 1).toString(),
//       };
//     }),
//   },
//   walkingTimePerOneTime: {
//     id: "walkingTimePerOneTime",
//     inputType: "selectBox",
//     title: "의 일주일 산책 횟수",
//     frontWord: "1회 당",
//     placeholder: "시간",
//     options: Array.from({ length: 6 }, (_, i) => {
//       const value = (i * 0.5 + 0.5).toString();
//       const label = i === 5 ? "3시간 이상" : formatTime(i * 0.5 + 0.5);
//       return {
//         label,
//         value,
//       };
//     }),
//   },
//   snackCountLevel: {
//     id: "snackCountLevel",
//     inputType: "button",
//     title: "의 간식량은 어떤가요?",
//     isMultiSelect: false,
//     options: [
//       { id: "snackCountLevel-LITTLE", value: "LITTLE", label: "적어요" },
//       { id: "snackCountLevel-NORMAL", value: "NORMAL", label: "적당해요" },
//       { id: "snackCountLevel-MUCH", value: "MUCH", label: "많아요" },
//     ],
//   },
//   waterCountLevel: {
//     id: "waterCountLevel",
//     inputType: "button",
//     title: "의 음수량은 어떤가요?",
//     isMultiSelect: false,
//     options: [
//       { id: "waterCountLevel-LITTLE", value: "LITTLE", label: "적어요" },
//       { id: "waterCountLevel-NORMAL", value: "NORMAL", label: "적당해요" },
//       { id: "waterCountLevel-MUCH", value: "MUCH", label: "많아요" },
//     ],
//   },
//   supplement: {
//     id: "supplement",
//     inputType: "button",
//     title: "의 현재 먹고 있는 영양제는 무엇인가요?",
//     isMultiSelect: true,
//     options: [
//       { id: "supplement-NONE", value: "NONE", label: "없어요" },
//       { id: "supplement-유산균", value: "유산균", label: "유산균" },
//       { id: "supplement-오메가", value: "오메가-3", label: "오메가-3" },
//       { id: "supplement-항산화", value: "항산화", label: "항산화" },
//       { id: "supplement-관절", value: "관절", label: "관절" },
//       { id: "supplement-눈", value: "눈", label: "눈" },
//       { id: "supplement-피부", value: "피부", label: "피부" },
//       { id: "supplement-면역력", value: "면역력", label: "면역력" },
//       { id: "supplement-심장", value: "심장", label: "심장" },
//       { id: "supplement-치아", value: "치아", label: "치아" },
//       { id: "supplement-종합", value: "종합", label: "종합" },
//       { id: "supplement-ETC", value: "ETC", label: "기타" },
//     ],
//   },
//   supplementEtc: {
//     id: "supplementEtc",
//     name: "supplementEtc",
//     placeholder: "선택지에 없는 경우 기재해주세요.",
//   },
//   inedibleFood: {
//     id: "inedibleFood",
//     inputType: "button",
//     title: "의 못 먹는 재료가 있나요?",
//     isMultiSelect: true,
//     options: [
//       { id: "inedibleFood-NONE", value: "NONE", label: "없어요" },
//       { id: "inedibleFood-닭", value: "닭", label: "닭" },
//       { id: "inedibleFood-칠면조", value: "칠면조", label: "칠면조" },
//       { id: "inedibleFood-소", value: "소", label: "소" },
//       { id: "inedibleFood-오리", value: "오리", label: "오리" },
//       { id: "inedibleFood-양", value: "양", label: "양" },
//       { id: "inedibleFood-ETC", value: "ETC", label: "기타" },
//     ],
//   },
//   inedibleFoodEtc: {
//     id: "inedibleFoodEtc",
//     name: "inedibleFoodEtc",
//     placeholder: "선택지에 없는 경우 기재해주세요.",
//   },
//   currentMeal: {
//     id: "currentMeal",
//     inputType: "button",
//     title: "의 현재 먹고 있는 식사는 어떤 것인가요?",
//     isMultiSelect: true,
//     options: [
//       { id: "currentMeal-건사료", value: "건사료", label: "건사료" },
//       {
//         id: "currentMeal-습식사료/캔",
//         value: "습식사료/캔",
//         label: "습식사료/캔",
//       },
//       { id: "currentMeal-생식", value: "생식", label: "생식" },
//       { id: "currentMeal-화식", value: "화식", label: "화식" },
//       { id: "currentMeal-수제사료", value: "수제사료", label: "수제사료" },
//       {
//         id: "currentMeal-동결건조사료",
//         value: "동결건조사료",
//         label: "동결건조사료",
//       },
//     ],
//   },
//   caution: {
//     id: "caution",
//     inputType: "button",
//     title: "의 건강적 특이사항, 질병이 있나요?",
//     isMultiSelect: true,
//     options: [
//       { id: "caution-NONE", value: "NONE", label: "없어요" },
//       { id: "caution-관절염", value: "관절염", label: "관절염" },
//       { id: "caution-슬개골 탈구", value: "슬개골 탈구", label: "슬개골 탈구" },
//       { id: "caution-피부염", value: "피부염", label: "피부염" },
//       { id: "caution-당뇨병", value: "당뇨병", label: "당뇨병" },
//       { id: "caution-귀 염증", value: "귀 염증", label: "귀 염증" },
//       { id: "caution-눈물/안구", value: "눈물/안구", label: "눈물/안구" },
//       { id: "caution-치주염", value: "치주염", label: "치주염" },
//       { id: "caution-신장 질환", value: "신장 질환", label: "신장 질환" },
//       { id: "caution-간 질환", value: "간 질환", label: "간 질환" },
//       { id: "caution-췌장염", value: "췌장염", label: "췌장염" },
//       { id: "caution-심장 질환", value: "심장 질환", label: "심장 질환" },
//       { id: "caution-기타", value: "ETC", label: "기타" },
//     ],
//   },
//   cautionEtc: {
//     id: "cautionEtc",
//     name: "cautionEtc",
//     placeholder: "선택지에 없는 경우 기재해주세요.",
//   },
//   newToRawDiet: {
//     id: "newToRawDiet",
//     inputType: "button",
//     title: "의 생식 급여가 처음인가요?",
//     isMultiSelect: false,
//     options: [
//       { id: "newToRawDiet-Yes", value: true, label: "네" },
//       { id: "newToRawDiet-NO", value: false, label: "아니요" },
//     ],
//   },
//   priorityConcerns: {
//     id: "priorityConcerns",
//     inputType: "button",
//     title: "의 고민되는 항목 우선 순위 3가지를 선택해주세요.",
//     isMultiSelect: true,
//     options: [
//       {
//         id: "recommendRecipeId-5",
//         value: "구토·설사·복통",
//         label: "구토·설사·복통",
//       },
//       { id: "recommendRecipeId-6", value: "체중 조절", label: "체중 조절" },
//       { id: "recommendRecipeId-7", value: "피로회복", label: "피로회복" },
//       { id: "recommendRecipeId-8", value: "눈물·눈곱", label: "눈물·눈곱" },
//       { id: "recommendRecipeId-9", value: "적은 음수량", label: "적은 음수량" },
//       { id: "recommendRecipeId-10", value: "피부·모질", label: "피부·모질" },
//       { id: "recommendRecipeId-11", value: "관절 건강", label: "관절 건강" },
//       { id: "recommendRecipeId-12", value: "자견 발육", label: "자견 발육" },
//       {
//         id: "recommendRecipeId-13",
//         value: "노령견 건강",
//         label: "노령견 건강",
//       },
//     ],
//   },
// } as const;
