export function buildGutCheckPayload(values: Record<string, any>) {
  const {
    step1: { bodyFit },
    step2: { probioticsStatus, probioticsProduct },
    step3: { antibioticsStatus },
    step4: { allergyStatus, allergenFoodList },
    step5: { pregnancyStatus },
    step6: { activityLevel },
    step7: { treatingDiseaseList },
    step8: { feedType },
    step9: { foodType },
    step10: { foodProduct, feedTime },
    step11: { defecationHabit },
    step12: { snackLevel },
    step13: { cohabitingPetList },
    step14: { supplementTypeList, supplementProduct },
    step15: { healthConcernTypeList },
    step16: { acquisitionType },
    step17: { otherComment },
  } = values;

  return {
    petId: 3532,
    kitId: 4,
    survey: {
      bodyFit,
      probioticsStatus,
      probioticsProduct,
      antibioticsStatus,
      allergyStatus,
      allergenFoodList,
      pregnancyStatus,
      activityLevel,
      treatingDiseaseList,
      feedType,
      foodType,
      foodProduct,
      feedTime,
      defecationHabit,
      snackLevel,
      cohabitingPetList,
      supplementTypeList,
      supplementProduct,
      healthConcernTypeList,
      acquisitionType,
      otherComment,
    },
  };
}
